#!/usr/bin/env python
# -*- coding: utf-8 -*-
# variable descriptions
lvarde = [
    ("COR-MCRP.n", "kg", "Total control poison mass in cell n."),
    ("COR-MCRP-TOT", "kg", "Total control poison in core."),
    ("COR-MINC.n", "kg", "Total Inconel mass in cell n."),
    ("COR-MINC-TOT", "kg", "Total Inconel in core."),
    ("COR-MSS.n", "kg", "Total steel mass in cell n."),
    ("COR-MSSOX.n", "kg", "Total steel oxide mass in cell n."),
    ("COR-MSS-TOT", "kg", "Total steel in core."),
    ("COR-MSX-TOT", "kg", "Total steel oxide in core."),
    ("COR-MUO2.n", "kg", "Total UO2 mass in cell n."),
    ("COR-MUO2-TOT", "kg", "Total UO2 in core."),
    ("COR-MZR.n", "kg", "Total Zircaloy mass in cell n."),
    ("COR-MZRO2.n", "kg", "Total ZrO2 mass in cell n."),
    ("COR-MZR-TOT", "kg", "Total Zircaloy in core."),
    ("COR-MZX-TOT", "kg", "Total ZrO2 in core."),
    (
        "COR-DC.m.k.n",
        "kg",
        "Conglomerate debris mass for material m on component k in cell n.",
    ),
    ("COR-PB.m.n", "kg", "Particulate debris mass for material m in bypass of cell n."),
    ("COR-PD.m.n", "kg", "Particulate debris mass for material m in cell n."),
    (
        "COR-M.m.k.n",
        "kg",
        "Total mass (intact plus conglomerate) of material m in component k in cell n.",
    ),
    ("COR-MUO2-FU.n", "kg", "Intact fuel UO2 mass in cell n."),
    ("COR-MZR-CL.n", "kg", "Intact cladding Zircaloy mass in cell n."),
    ("COR-MZR-CN.n", "kg", "Intact canister (including CB) Zircaloy mass in cell n."),
    ("COR-MSS-OS.n", "kg", "Intact other structure (OS) steel mass in cell n."),
    (
        "COR-MCRP-OS.n",
        "kg",
        "Intact other structure (OS) control poison mass in cell n.",
    ),
    ("COR-MZRO2-CL.n", "kg", "Intact cladding ZrO2 mass in cell n."),
    ("COR-MZRO2-CN.n", "kg", "Intact canister (including CB) ZrO2 mass in cell n."),
    ("COR-MSSOX-OS.n", "kg", "Intact other structure steel oxide mass in cell n."),
    ("COR-MUO2-DB.n", "kg", "Total UO2 debris mass in cell n."),
    ("COR-MZR-DB.n", "kg", "Total Zircaloy debris mass in cell n."),
    ("COR-MSS-DB.n", "kg", "Total steel debris mass in cell n."),
    ("COR-MZRO2-DB.n", "kg", "Total ZrO2 debris mass in cell n."),
    ("COR-MSSOX-DB.n", "kg", "Total steel oxide debris mass in cell n."),
    ("COR-MCRP-DB.n", "kg", "Total control poison debris mass in cell n."),
    (
        "COR-AFLMIN.m.n",
        "m2",
        "Minimum flow area open between core cells m and n, inclusive (channel and bypass combined for BWR).",
    ),
    (
        "COR-VOL-FLU.n",
        "m3",
        'Volume of fluid ("empty volume") in cell n (total for BWR).',
    ),
    ("COR-VOL-FLUB.n", "m3", "Volume of fluid in bypass of cell n (zero for PWR)."),
    ("COR-VOL-FLUC.n", "m3", "Volume of fluid in channel of cell n (total for PWR)."),
    ("COR-VOLF-FU.n", "none", "Intact fuel volume fraction in cell n."),
    ("COR-VOLF-CL.n", "none", "Cladding volume fraction in cell n."),
    ("COR-VOLF-CN.n", "none", "Canister volume fraction in cell n."),
    ("COR-VOLF-OS.n", "none", 'OS "other structure" volume fraction in cell n.'),
    ("COR-VOLF-SS.n", "none", "Supporting structure volume fraction in cell n."),
    ("COR-VOLF-NS.n", "none", "Nonsupporting structure volume fraction in cell n."),
    (
        "COR-VOLF-PB.n",
        "none",
        "Particulate debris volume fraction in bypass of cell n.",
    ),
    ("COR-VOLF-PD.n", "none", "Particulate debris volume fraction in cell n."),
    ("COR-VOLF-FLB.n", "none", "Fluid volume fraction in cell bypass of cell n."),
    (
        "COR-VOLF-FLC.n",
        "none",
        "Fluid volume fraction in channel of cell n (BWR only).",
    ),
    ("COR-VOLF-FL.n", "none", "Fluid volume fraction in cell n."),
    ("COR-TFU.n", "K", "Temperature of UO2 in cell n."),
    ("COR-TCL.n", "K", "Temperature of Zircaloy cladding in cell n."),
    (
        "COR-TCN.n",
        "K",
        "Temperature of canister (the part not adjacent to the control blade) in cell n.",
    ),
    ("COR-TCB.n", "K", "Temperature of canister adjacent to control blade."),
    ("COR-TOS.n", "K", 'Temperature of OS "other structure" in cell n.'),
    ("COR-TSS.n", "K", "Temperature of supporting structure in cell n."),
    ("COR-TNS.n", "K", "Temperature of nonsupporting structure in cell n."),
    ("COR-TPB.n", "K", "Temperature of particulate debris in bypass cell n."),
    ("COR-TPD.n", "K", "Temperature of particulate debris in cell n."),
    ("COR-TSVC.n", "K", "Local channel fluid temperature seen by cell n."),
    ("COR-TSVB.n", "K", "Local bypass fluid temperature seen by cell n."),
    (
        "COR-MLTFR.n.m.k",
        "none",
        "Melt fraction of material number m in component number k in cell n.",
    ),
    ("COR-ENERGY-TOT", "J", "Total internal energy in COR package."),
    (
        "COR-EFPD-TOT",
        "J",
        "Total cumulative fission power and decay heat generated in core.",
    ),
    ("COR-EMWR-TOT", "J", "Total cumulative oxidation heat generated in core."),
    ("COR-EB4C-TOT", "J", "Total cumulative heat from B4C reactions in core."),
    ("COR-ECNV-TOT", "J", "Total cumulative energy transfer to CVH package."),
    ("COR-EBND-TOT", "J", "Total cumulative energy transfer to HS package."),
    (
        "COR-EFPD-RAT",
        "W",
        "Total fission power and decay heat generation rate in core.",
    ),
    ("COR-EMWR-RAT", "W", "Total oxidation heat generation rate in core."),
    ("COR-EB4C-RAT", "W", "Total heat generation rate from B4C reactions in core."),
    ("COR-ECNV-RAT", "W", "Total convective heat generation rate in core."),
    (
        "COR-EBND-RAT",
        "W",
        "Total radiative heat transfer rate to boundary heat structures.",
    ),
    ("COR-QCNV.m", "W", "Heat transfer rate to atmosphere in fluid volume m."),
    (
        "COR-HTCLH.i",
        "W/m2-K",
        "Heat transfer coefficient from ring i of lower head to water pool.",
    ),
    (
        "COR-HTCLH-AVG",
        "W/m2-K",
        "Average heat transfer coefficient from lower head to water pool.",
    ),
    ("COR-QFLXLH.i", "W/m2-K", "Heat flux from ring i of lower head to water pool."),
    ("COR-QFLXLH-AVG", "W/m2-K", "Average heat flux from lower head to water pool."),
    (
        "COR-QTOTLH.i",
        "J",
        "Cumulative heat transferred from ring i of lower head to water pool.",
    ),
    (
        "COR-QTOTLH-TOT",
        "J",
        "Total cumulative heat transferred from lower head to water pool.",
    ),
    ("COR-SS-STRESS.ijj", "Pa", "Maximum component of stress in SS in core cell ijj."),
    (
        "COR-SS-DAMAGE.ijj",
        "none",
        "Damage fraction (fraction of damage that will produce failure) for SS in core cell ijj.",
    ),
    (
        "COR-SS-TLEFT.ijj",
        "s",
        "Remaining life for SS in core cell ijj (for unchanged temperature and load).",
    ),
    ("COR-DMH2-TOT", "kg", "Total cumulative hydrogen production in core."),
    ("COR-DMCO-TOT", "kg", "Total cumulative carbon monoxide production in core."),
    (
        "COR-DMCO2-TOT",
        "kg",
        "Total cumulative carbon dioxide production in core (available only for MCRP = 'B4C').",
    ),
    (
        "COR-DMCH4-TOT",
        "kg",
        "Total cumulative methane production in core (available only for MCRP = 'B4C').",
    ),
    ("COR-MCTOHS-TOT", "kg", "Total mass added to HS by COR."),
    ("COR-ECTOHS-TOT", "J", "Total enthalpy of mass added to HS by COR."),
    ("COR-MCTOBH-TOT", "kg", "Total mass added to BH by COR."),
    ("COR-ECTOBH-TOT", "J", "Total enthalpy of mass added to BH by COR."),
    ("COR-RCTOBH-TOT", "J", "Total energy radiated to BH debris by COR."),
    ("COR-TPN.n", "K", "Temperature of penetration n."),
    ("COR-TLH.ijj", "K", "Temperature of vessel lower head node."),
    ("COR-VSTRAIN.ijj", "dimensionless", "Plastic strain in vessel lower head node."),
    ("COR-VSTRESS.ijj", "Pa", "Stress in vessel lower head node."),
    ("COR-ABRCH", "m2", "Total flow area of vessel breach."),
    ("COR-MEJEC-TOT", "kg", "Total debris mass ejected through vessel breach."),
    ("COR-DT", "s", "COR package time step."),
    ("COR-NCYCLE", "none", "Total number of COR package subcycles."),
    ("COR-CPU", "s", "Total CPU usage by run portion of COR package."),
    ("COR-MASSERR", "kg", "Total mass error for COR package."),
    ("COR-ENERGYERR", "J", "Total energy error for COR package."),
    (
        "COR-REL-ENGY-ERR",
        "dimensionless",
        "COR relative energy error, defined as COR-ENERGYERR/ COR-ENERGY-TOT",
    ),
    (
        "COR-REL-ENGY-ERM",
        "dimensionless",
        "COR relative energy error, modified to include enthalpy of mass transfers to BH and HS, defined as COR-ENERGYERR/(COR-ENERGY-TOT + debris to BH and CAV)",
    ),
    ("COR-CRUST-THICK", "m", "Thickness of crust formed at lower head (by segment)"),
    ("CVH-CLIQLEV.n", "m", "Collapsed liquid elevation in control volume n."),
    (
        "CVH-CPUT",
        "s",
        "Total CPU usage by the RUN (time-advancement) portion of CVH package",
    ),
    ("CVH-CPUE", "s", "CPU usage for edit in RUN portion of CVH package."),
    ("CVH-CPUC", "s", "CPU usage for calculations in RUN portion of CVH package."),
    (
        "CVH-CPUR",
        "s",
        "CPU usage to process restart file in RUN portion of CVH package.",
    ),
    ("CVH-E.n", "J/kg", "Specific internal energy in control volume n."),
    (
        "CVH-E.m.n",
        "J/kg",
        "Specific internal energy of material m in control volume n.",
    ),
    ("CVH-ECV.n", "J", "Total internal energy in control volume n."),
    ("CVH-ECV.m.n", "J", "Total internal energy of material m in control volume n."),
    ("CVH-H.n", "J/kg", "Specific enthalpy in control volume n."),
    ("CVH-H.m.n", "J/kg", "Specific enthalpy of material m in control volume n."),
    ("CVH-LIQLEV.n", "m", "Swollen liquid elevation in control volume n."),
    ("CVH-MASS.n", "kg", "Mass of material in control volume n."),
    ("CVH-MASS.m.n", "kg", "Mass of material m in control volume n."),
    ("CVH-P.n", "Pa", "Pressure of control volume n."),
    ("CVH-PPART.m.n", "Pa", "Partial pressure of material m in control volume n."),
    (
        "CVH-PSAT(TLIQ).n",
        "Pa",
        "Saturation pressure of water at pool temperature in control volume n.",
    ),
    (
        "CVH-PSAT(TVAP).n",
        "Pa",
        "Saturation pressure of water at atmosphere temperature in control volume n.",
    ),
    (
        "CVH-QUALITY.n",
        "dimensionless",
        "Quality (non-pool, non-fog mass fraction) in control volume n",
    ),
    ("CVH-RHO.n", "kg/m3", "Net mass density of all materials in control volume n."),
    ("CVH-RHO.m.n", "kg/m3", "Mass density of material m in control volume n."),
    ("CVH-RHOA.n", "kg/m3", "Mass density of atmosphere in control volume n."),
    ("CVH-RHOP.n", "kg/m3", "Mass density of pool in control volume n."),
    ("CVH-TLIQ.n", "K", "Pool temperature in control volume n."),
    (
        "CVH-TOT-E",
        "J",
        "Total internal energy in the control volume hydrodynamics package.",
    ),
    (
        "CVH-TOT-E.m",
        "J",
        "Total internal energy of material m in the control volume hydrodynamics package.",
    ),
    ("CVH-TOT-M", "kg", "Total mass in the control volume hydrodynamics package."),
    (
        "CVH-TOT-M.m",
        "kg",
        "Total mass of material m in the control volume hydrodynamics package.",
    ),
    (
        "CVH-TSAT(A).n",
        "K",
        "Water saturation temperature at the partial pressure of water vapor in the atmosphere of control volume n.",
    ),
    (
        "CVH-TSAT(P).n",
        "K",
        "Water saturation temperature at the pressure of control volume n.",
    ),
    ("CVH-TVAP.n", "K", "Atmosphere temperature in control volume n."),
    ("CVH-VELVAPCV.n", "m/s", "Velocity of atmosphere in control volume n."),
    ("CVH-VELLIQCV.n", "m/s", "Velocity of pool in control volume n. (units = m/s)"),
    ("CVH-VIRVOVAP.n", "m3", "Virtual volume in atmosphere in control volume n."),
    ("CVH-VIRVOLIQ.n", "m3", "Virtual volume in pool in control volume n."),
    (
        "CVH-VOID.n",
        "dimensionless",
        "Void (non-pool) volume fraction in control volume n.",
    ),
    ("CVH-VOLFOG.n", "m3", "Volume of fog in control volume n."),
    (
        "CVH-VOLLIQ.n",
        "m3",
        "Swollen volume of pool (including any vapor bubbles) in control volume n.",
    ),
    ("CVH-VOLVAP.n", "m3", "Volume of gaseous atmosphere in control volume n."),
    (
        "CVH-X.m.n",
        "dimensionless",
        "Mole fraction of gaseous material m (m 3) in the atmosphere of control volume n.",
    ),
    (
        "FL-EFLOW.x.n",
        "W",
        "Enthalpy flow rate of pool (x='P') or atmosphere (x='A') flow through flow path n, with respect to the normal MELCOR reference point.",
    ),
    (
        "FL-FRUNBLK.n",
        "dimensionless",
        "Fraction of flow path that is unblocked by core debris. This variable is available only for flowpaths where the flow blockage model has been invoked by inclusion of a FLnnnBk record as part of MELGEN input; for flowpaths whose area is controlled by an ordinary valve, the open fraction may be plotted as the value of the related control function, CFVALU.m.",
    ),
    (
        "FL-I-EFLOW.x.n",
        "J",
        "Integral of enthalpy associated with pool (x='P') or atmosphere (x='A') flow through flow path n, with respect to the normal MELCOR reference point.",
    ),
    (
        "FL-I-H2O-MFLOW.n",
        "kg",
        "Integral of mass of water (pool + fog + vapor) flowing through flow path n.",
    ),
    (
        "FL-I-MFLOW.m.n",
        "kg",
        "Integral of mass of material m flowing through flow path n.",
    ),
    (
        "FL-MFLOW.n",
        "kg/s",
        "Total mass flow rate (all hydrodynamic materials) through flow path n.",
    ),
    ("FL-MFLOW.m.n", "kg/s", "Mass flow rate of material m through flow path n."),
    (
        "FL-V-N-OC.n",
        "dimensionless",
        'Number of times valve number n has opened or closed. Any area fraction greater than 0.0 is considered "open".',
    ),
    ("FL-VELLIQ.n", "m/s", "Velocity of pool through flow path n."),
    ("FL-VELVAP.n", "m/s", "Velocity of atmosphere through flow path n."),
    ("FL-VOID.n", "dimensionless", "Void fraction in flow path n."),
    ("SPR-TP.n", "K", "Temperature of spray droplets from source n"),
    ("SPR-FL.n", "m3/s", "Flow rate of spray droplets from source n"),
    (
        "SPR-HTTRAN.j",
        "W",
        "Rate of heat transfer from sprays to steam in control volume j.",
    ),
    (
        "SPR-MSTRAN.j",
        "kg/s",
        "Rate of mass transfer from sprays to steam in control volume j",
    ),
    (
        "SPR-SUMPHT.j",
        "W",
        "Rate of heat transfer from sprays to pool in sump control volume j",
    ),
    (
        "SPR-SUMPMS.j",
        "kg/s",
        "Rate of mass transfer from sprays to pool in sump control volume j",
    ),
    ("DCH-COREPOW.0", "W", "Whole-core decay heat power."),
    (
        "DCH-CLSPOW.n",
        "W/kg",
        "Decay heat power per unit mass for radionuclide class n.",
    ),
    ("DCH-TOTCLSPOW.0", "W", "Total decay heat power for all radionuclide classes."),
    ("CAV-ACTIVE.n", "(logical", "Activity flag for cavity n."),
    ("CAV-MTOT.n", "kg", "Total mass in cavity n."),
    ("CAV-HTOT.n", "J", "Total enthalpy for cavity n."),
    ("CAV-DHR.n", "W", "Decay heat rate for cavity n."),
    (
        "CAV-MASS.spc.n",
        "kg",
        "Total mass of requested condensed-phase species in cavity n (summed over all debris layers).",
    ),
    ("CAV-M.lay.n", "kg", "Mass of layer."),
    ("CAV-T.lay.n", "K", "Layer temperature."),
    ("CAV-RHO.lay.n", "kg/m3", "Layer density."),
    ("CAV-THICK.lay.n", "m", "Layer thickness."),
    ("CAV-VOL.lay.n", "m3", "Volume occupied by layer."),
    ("CAV-VF.lay.n", "dimensionless", "Layer void fraction."),
    ("CAV-MAXRAD.n", "m", "Maximum cavity radius."),
    ("CAV-MINALT.n", "m", "Minimum cavity altitude."),
    ("CAV-TMEX.n", "kg", "Total mass of gas released from cavity n."),
    ("CAV-MEX.gas.n", "kg", "Total mass of requested gas released from cavity n."),
    ("CAV-QREA.n", "W", "Heating rate by chemical reactions in cavity n."),
    (
        "CAV-QCNCT.n",
        "W",
        "Heat loss to concrete in cavity n. Under the assumptions of CORCON-MOD2, this heat goes to the ablation of concrete.",
    ),
    (
        "CAV-QSURF.n",
        "W",
        "Heat loss from the surface of debris in cavity n. It may go to either a pool or the atmosphere in the bounding control volume.",
    ),
    ("CAV-TGASMOL.n", "mol", "Total moles of gas released from cavity n."),
    ("CAV-R.n.i", "m", "Radial coordinate of i-th body point in cavity n."),
    ("CAV-Z.n.i", "m", "Axial coordinate of i-th body point in cavity n."),
    (
        "CAV-CPUT",
        "s",
        "Total CPU time used in Cavity package, including computation and I/O.",
    ),
    ("CAV-CPUC", "s", "CPU time used for computation in Cavity package."),
    ("bh-cpu", "s", "Total CPU usage required in executing the BH Package ."),
    (
        "bh-gas-ener.n",
        "j",
        "Cumulative gas enthalpy released or extracted by the BH Package during gas release. n = 1 for the lower plenum atmosphere. n = 2 for the containment atmosphere .",
    ),
    (
        "bh-gsms-lh.n",
        "kg",
        "Cumulative gas mass extracted from the lower plenum atmosphere by the BH Package for n = 1 to nmmat gases; the gas indices are identified in the printed output for the BH Package.",
    ),
    (
        "bh-gsms-dw.n",
        "kg",
        "Cumulative gas mass exhausted into the containment atmosphere by the BH Package for n = 1 to nmmat gases; the gas indices are identified in the printed output for the BH Package.",
    ),
    (
        "bh-rad-ener",
        "j Cumulative energy added to the lower plenum atmosphere by the BH Package. Before failure and collapse of the lower plenum structures, this variable may be negative. This is due to the large thermal mass and surface area of these cold structures at the time of lower plenum dryout and, thus, their cooling effect on the lower plenum atmosphere. After they fail and collapse into the lower plenum debris bed, the lower plenum atmosphere rapidly heats due to radiative exchange from the surface of the debris bed and this variable becomes positive",
        ".",
    ),
    (
        "bh-jp-ener",
        "j",
        "Cumulative energy added to the water pool in the downcomer by the BH package .",
    ),
    (
        "bh-cav-ener",
        "j",
        "Cumulative energy added to the reactor cavity CVH volume (ICVCAV) atmosphere since the initiation of the BH Package.",
    ),
    (
        "bh-dwl-ener",
        "j",
        "Cumulative energy added to the containment CVH volume (ICVDWS) atmosphere immediately above the reactor vessel skirt since the initiation of the BH Package.",
    ),
    (
        "bh-pour-temp",
        "K",
        "Temperature of debris pouring from the reactor vessel bottom head over a system cycle .",
    ),
    (
        "bh-species-rate.index*",
        "kg/s",
        "Rate of species’ mass ejection as calculated by the BH Package; if no ejection is calculated, then 0.0 is plotted .",
    ),
    (
        "bh-oxides-rate",
        "kg/s",
        "Rate of oxide mass ejection from the lower plenum as calculated by BH; represents the sum of species flows for species 10 to 18 .",
    ),
    (
        "bh-metals-rate",
        "kg/s",
        "Rate of metal mass ejection from the lower plenum as calculated by BH; represents the sum of species flows for species 1 to 9.",
    ),
    (
        "bh-total-rate",
        "kg/s",
        "Total rate of debris ejection from the lower plenum as calculated by BH summed over species 1 to 18.",
    ),
    ("bh-ex-ves-dk-pow", "Not currently available.", ""),
    (
        "bh-species-cumul.index*",
        "kg",
        "Cumulative mass of debris species ejected from the reactor vessel.",
    ),
    (
        "bh-oxides-cumul",
        "kg",
        "Cumulative mass of oxidic debris ejected from the reactor vessel summed over species 10 to 18 .",
    ),
    (
        "bh-metals-cumul",
        "kg",
        "Cumulative mass of metallic debris ejected from the reactor vessel summed over species 1 to 9.",
    ),
    (
        "bh-debris-cumul",
        "kg",
        "Cumulative debris mass ejected from the reactor vessel summed over species 1 to 18.",
    ),
    (
        "bh-wall-power-nn",
        "W",
        "Instantaneous heat transfer rate for BH package bottom head node nn external surface (01 nn 18).",
    ),
    (
        "bh-fflag",
        "none",
        "Flag switching from 0.0 to 1.0 to indicate gross failure of the bottom head wall by either creep rupture or ablation. This control function is useful in controlling a “valve” in a CVH/FL flow path. If such a flow path between the lower plenum and containment CVH volumes is not specified, then there is no gas or water pool flow from the lower plenum to the containment after gross failure of the bottom head wall.",
    ),
    (
        "bh-cond-pow",
        "W",
        "Conduction power calculated from node NWALL of the BH package wall model to IHSTOP of the HS Package (see input record BH1700).",
    ),
    (
        "bh-shroud-mass.i",
        "kg",
        "mass of core boundary structures represented by the BH Package after failure of the core boundary structure ; 1 I (NSHDLP+1) where I is the structure index having the following meaning:blank for PWR; 1 baffle plate for BWR; 2 lowermost core boundary segment; NSHDLP core boundary segment immediately below the core plate location; NSHDLP+1, entire core boundary portion above the core plate.",
    ),
    (
        "bh-shroud-temp.i",
        "K",
        "Temperature of core boundary structures represented by the BH Package after failure of the core boundary; 1 I (NSHDLP+1); see plot variable 22 for definition of I.",
    ),
    (
        "bh-shroud-tmlt",
        "kg",
        "Total mass of core boundary that has melted and relocated into the core or the lower plenum regions after dryout of the downcomer annulus.",
    ),
    (
        "bh-lp-water-mass",
        "kg",
        "Lower plenum water mass present in the BH package model of debris/water pool interactions .",
    ),
    (
        "bh-lp-water-temp",
        "K",
        "Temperature of the lower plenum water pool mass present in the BH package model of debris/water pool interactions.",
    ),
    (
        "bh-accum-mass",
        "kg",
        "Instantaneous mass of all debris that has left the core region but that has not yet entered the BH package lower plenum debris bed.",
    ),
    (
        "bh-fprls-rate.n",
        "kg/s",
        "Instantaneous elemental radioactive class release (e.g., fission products) rate of RN package class n summed over all control volumes of the BH debris bed; does not include nonradioactive released masses associated with class n; see RN Package Users’ Guide for RN class definitions.",
    ),
    (
        "bh-fprls-cum.n",
        "kg",
        "Cumulative elemental radioactive (e.g., fission product) class release of RN package class n summed over all control volumes of the BH debris bed; does not include nonradioactive released masses associated with class n; see RN Package Users’ Guide for RN class definitions.",
    ),
    (
        "bh-energy-err",
        "J",
        "BH package energy error; see Section 11.4.4 of the BH Package Reference Manual.",
    ),
    (
        "bh-rel-engy-err",
        "?",
        "BH package relative energy error; see Section 11.4.4 of the BH Package Reference Manual",
    ),
    (
        "CFVALU.n",
        "?",
        "Value of control function n. At present, only real-valued control functions can be plotted.",
    ),
    (
        "EDF.n.m",
        "?",
        'Value of the mth data channel in external data file n. If the data are plotted, the units will be given (by default) as "UNK" because they are not—and cannot be—known by EDF. The user may, of course, specify the correct units by defining a nondefault axis label as part of the input to the plot program.',
    ),
    (
        "FDI-FMREL.n",
        "kg",
        "Mass of material released to CORCON from FDI location n for this time step.",
    ),
    (
        "FDI-FMRELT.n",
        "kg",
        "Integrated mass released to CORCON from FDI location n for entire calculation.",
    ),
    (
        "FDI-ETRAN.n",
        "J",
        "Energy transferred to water from FDI location n for this time step.",
    ),
    (
        "FDI-ETRANT.n",
        "J",
        "Integrated energy transferred to water from FDI location n for entire calculation.",
    ),
    (
        "FDI-STGEN.n",
        "kg",
        "Mass of steam generated in FDI location n for this time step.",
    ),
    (
        "FDI-STGENT.n",
        "kg",
        "Integrated steam mass generation for FDI location n for entire calculation.",
    ),
    (
        "FDI-ZR-OXRAT.n.m",
        "kg/s",
        "Zircaloy oxidation rate in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ZR-OXTOT.n.m",
        "kg",
        "Integral over time of the zircaloy oxidation rate in CVH volume m for FDI location n.",
    ),
    (
        "FDI-AL-OXRAT.n.m",
        "kg/s",
        "Aluminum oxidation rate in CVH volume m for FDI location n.",
    ),
    (
        "FDI-AL-OXTOT.n.m",
        "kg",
        "Integral over time of the aluminum oxidation rate in CVH volume m for FDI location n.",
    ),
    (
        "FDI-SS-OXRAT.n.m",
        "kg/s",
        "Steel oxidation rate in CVH volume m for FDI location n.",
    ),
    (
        "FDI-SS-OXTOT.n.m",
        "kg",
        "Integral over time of the steel oxidation rate in CVH volume m for FDI location n.",
    ),
    (
        "FDI-O2-OXRAT.n.m",
        "kg/s",
        "Oxygen consumption rate in CVH volume m for FDI location n.",
    ),
    (
        "FDI-O2-OXTOT.n.m",
        "kg",
        "Integral over time of the oxygen consumption rate in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ST-OXRAT.n.m",
        "kg/s",
        "Steam consumption rate in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ST-OXTOT.n.m",
        "kg",
        "Integral over time of the steam consumption rate in CVH volume m for FDI location n.",
    ),
    (
        "FDI-H2-OXRAT.n.m",
        "kg/s",
        "Hydrogen generation rate in CVH volume m for FDI location n.",
    ),
    (
        "FDI-H2-OXTOT.n.m",
        "kg",
        "Integral over time of the hydrogen generation rate in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ATM-POWR.n.m",
        "W",
        "Heat transfer rate to atmosphere in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ATM-HEAT.n.m",
        "J",
        "Heat transferred to atmosphere in CVH volume m for FDI location n.",
    ),
    (
        "FDI-DEBRIS-T.n.m",
        "K",
        "Airborne debris temperature in CVH volume m for FDI location n.",
    ),
    (
        "FDI-OX-ENRGY.n.m",
        "J",
        "Energy generated by the oxidation of zircaloy and steel in CVH volume m for FDI location n.",
    ),
    (
        "FDI-MASS-ADD.n.m",
        "kg",
        "Mass transferred from TP package to CVH volume m for FDI location n.",
    ),
    (
        "FDI-ENTH-ADD.n.m",
        "J",
        "Enthalpy transferred from TP package to CVH volume m for FDI location n.",
    ),
    (
        "FDI-ATM-ZRM.n.m",
        "kg",
        "Airborne mass of zircaloy in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ATM-ZRX.n.m",
        "kg",
        "Airborne mass of ZrO2 in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ATM-UO2.n.m",
        "kg",
        "Airborne mass of UO2 in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ATM-SSM.n.m",
        "kg",
        "Airborne mass of steel in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ATM-SSX.n.m",
        "kg",
        "Airborne mass of steel oxide in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ATM-ALM.n.m",
        "kg",
        "Airborne mass of aluminum in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ATM-ALX.n.m",
        "kg",
        "Airborne mass of Al2O3 in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ATM-UMT.n.m",
        "kg",
        "Airborne mass of uranium metal in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ATM-CDM.n.m",
        "kg",
        "Airborne mass of cadmium in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ATM-B4C.n.m",
        "kg",
        "Airborne mass of boron carbide in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ATM-AIC.n.m",
        "kg",
        "Airborne mass of Ag-In-Cd in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ATM-ALL.n.m",
        "kg",
        "Airborne mass of all components in CVH volume m for FDI location n.",
    ),
    (
        "FDI-ZR-SXRAT.s.n.k",
        "kg/s",
        "Zircaloy oxidation rate on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-ZR-SXTOT.s.n.k",
        "kg",
        "Integral over time of the zircaloy oxidation rate on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-AL-SXRAT.s.n.k",
        "kg/s",
        "Aluminum oxidation rate on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-AL-SXTOT.s.n.k",
        "kg",
        "Integral over time of the aluminum oxidation rate on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SS-SXRAT.s.n.k",
        "kg/s",
        "Steel oxidation rate on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SS-SXTOT.s.n.k",
        "kg",
        "Integral over time of the steel oxidation rate on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-O2-SXRAT.s.n.k",
        "kg/s",
        "Oxygen consumption rate on the s side of HS structurek for FDI location n.",
    ),
    (
        "FDI-O2-SXTOT.s.n.k",
        "kg",
        "Integral over time of the oxygen consumption rate on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-ST-SXRAT.s.n.k",
        "kg/s",
        "Steam consumption rate on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-ST-SXTOT.s.n.k",
        "kg",
        "Integral over time of the steam consumption rate on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-H2-SXRAT.s.n.k",
        "kg/s",
        "Hydrogen generation rate on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-H2-SXTOT.s.n.k",
        "kg",
        "Integral over time of the hydrogen generation rate on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SRF-POWR.s.n.k",
        "W",
        "Heat transfer rate to the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SRF-HEAT.s.n.k",
        "J",
        "Heat transferred to the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-TDB-SURF.s.n.k",
        "K",
        "Temperature of deposited debris on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SX-ENRGY.s.n.k",
        "J",
        "Energy generated by the oxidation of metals on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-MASS-SET.s.n.k",
        "kg",
        "Total mass that has settled out of the atmosphere onto the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-ENTH-SET.s.n.k",
        "J",
        "Total enthalpy that has settled out of the atmosphere onto the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SRF-ZRM.s.n.k",
        "kg",
        "Mass of Zircaloy on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SRF-ZRX.s.n.k",
        "kg",
        "Mass of ZrO2 on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SRF-UO2.s.n.k",
        "kg",
        "Mass of UO2 on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SRF-SSM.s.n.k",
        "kg",
        "Mass of steel on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SRF-SSX.s.n.k",
        "kg",
        "Mass of steel oxide on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SRF-ALM.s.n.k",
        "kg",
        "Mass of aluminum on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SRF-ALX.s.n.k",
        "kg",
        "Mass of Al2O3 on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SRF-UMT.s.n.k",
        "kg",
        "Mass of uranium metal on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SRF-CDM.s.n.k",
        "kg",
        "Mass of cadmium on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SRF-B4C.s.n.k",
        "kg",
        "Mass of boron carbide on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SRF-AIC.s.n.k",
        "kg",
        "Mass of Ag-In-Cd on the s side of HS structure k for FDI location n.",
    ),
    (
        "FDI-SRF-ALL.s.n.k",
        "kg",
        "Mass of all components on the s side of HS structure k for FDI location n.",
    ),
    ("FDI-CPU", "s", "Total CPU time used for FDI package calculations"),
    ("HS-CPUC", "s", "total CPU time used for HS package calculations"),
    ("HS-CPUE", "s", "total CPU time used for HS package edits"),
    ("HS-CPUR", "s", "total CPU time used for HS package restarts"),
    (
        "HS-DEGAS-ENERGY.GGGGG",
        "J",
        "total energy of released gas from Gas Source GGGGG",
    ),
    ("HS-DEGAS-MASS.GGGGG", "kg", "total mass of released gas from Gas Source GGGGG"),
    ("HS-DEGAS-RATE.GGGGG", "kg/s", "degassing rate of Gas Source GGGGG"),
    (
        "HS-DEGAS-STEELM-GGGGG",
        "kg",
        "steel mass melted during the system cycle for steel degassing source GGGGG",
    ),
    (
        "HS-DEGAS-CSTEELM-GGGGG",
        "kg",
        "cumulative mass of steel melted for steel degassing source GGGGG",
    ),
    (
        "HS-DELE-ATMS-L.CCCCC",
        "J",
        "integrated energy transfer to boundary volume atmosphere of left (inside) boundary surface of Heat Structure CCCCC due to mass transfer",
    ),
    (
        "HS-DELE-ATMS-R.CCCCC",
        "J",
        "integrated energy transfer to boundary volume atmosphere of right (outside) boundary surface of Heat Structure CCCCC due to mass transfer",
    ),
    (
        "HS-DELE-POOL-L.CCCCC",
        "J",
        "integrated energy transfer to boundary volume pool of left (inside) boundary surface of Heat Structure CCCCC due to mass transfer",
    ),
    (
        "HS-DELE-POOL-R.CCCCC",
        "J",
        "integrated energy transfer to boundary volume pool of right (outside) boundary surface of Heat Structure CCCCC due to mass transfer",
    ),
    (
        "HS-FILM-TEMP-L.CCCCC",
        "K",
        "temperature of film/atmosphere interface at left boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-FILM-TEMP-R.CCCCC",
        "K",
        "temperature of film/atmosphere interface at right boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-DELM-DROP-L.CCCCC",
        "kg",
        "integrated droplet (fog) mass transfer to boundary volume atmosphere of left (inside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-DELM-DROP-R.CCCCC",
        "kg",
        "integrated droplet (fog) mass transfer to boundary volume atmosphere of right (outside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-DELM-POOL-L.CCCCC",
        "kg",
        "integrated water mass transfer to boundary volume pool of left (inside) boundary surface of Heat Structure CCCCC .",
    ),
    (
        "HS-DELM-POOL-R.CCCCC",
        "kg",
        "integrated water mass transfer to boundary volume pool of right (outside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-DELM-STEAM-L.CCCCC",
        "kg",
        "integrated vapor (steam) mass transfer to boundary volume atmosphere of left (inside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-DELM-STEAM-R.CCCCC",
        "kg",
        "integrated vapor (steam) mass transfer to boundary volume atmosphere of right (outside) boundary surface of Heat Structure CCCCC.",
    ),
    (
        "HS-ENERGY-FLUX-L.CCCCC",
        "W/m2",
        "energy flux associated withHS-MASS-FLUX-L.CCCCC.",
    ),
    (
        "HS-ENERGY-FLUX-R.CCCCC",
        "W/m2",
        "energy flux associated with HS-MASS-FLUX-R.CCCCC",
    ),
    (
        "HS-ENERGY-INPUT.CCCCC",
        "J",
        "energy input to Heat Structure CCCCC by internal and surface power sources and by other packages",
    ),
    ("HS-ENERGY-STORED.CCCCC", "J", "stored energy of Heat Structure CCCCC"),
    (
        "HS-FILM-ENTH-L.CCCCC",
        "J/kg",
        "specific enthalpy of liquid film on left (inside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-FILM-ENTH-R.CCCCC",
        "J/kg",
        "specific enthalpy of liquid film on right (outside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-FILM-MASS-L.CCCCC",
        "kg",
        "mass of liquid film on left (inside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-FILM-MASS-R.CCCCC",
        "kg",
        "mass of liquid film on right (outside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-FILM-THICK-L.CCCCC",
        "m",
        "thickness of liquid film on left (inside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-FILM-THICK-R.CCCCC",
        "m",
        "thickness of liquid film on right (outside) boundary surface of Heat Structure CCCCC .",
    ),
    (
        "HS-HTC-ATMS-L.CCCCC",
        "W/m2K",
        "atmosphere heat transfer coefficient at left (inside) boundary surface of Heat Structure CCCCC.",
    ),
    (
        "HS-HTC-ATMS-R.CCCCC",
        "W/m2K",
        "atmosphere heat transfer coefficient at right (outside) boundary surface of Heat Structure CCCCC.",
    ),
    (
        "HS-HTC-POOL-L.CCCCC",
        "W/m2K",
        "pool heat transfer coefficient at left (inside) boundary surface of Heat Structure CCCCC.",
    ),
    (
        "HS-HTC-POOL-R.CCCCC",
        "W/m2K",
        "pool heat transfer coefficient at right (outside) boundary surface of Heat Structure CCCCC",
    ),
    ("HS-ITER-FREQ", "none", "average iteration frequency over all heat structures"),
    (
        "HS-MASS-FLUX-L.CCCCC",
        "kg/m2s",
        "mass flux to left (inside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-MASS-FLUX-R.CCCCC",
        "kg/m2s",
        "mass flux to right (outside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-MTC-L.CCCCC",
        "m/s",
        "diffusion mass transfer coefficient at left (inside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-MTC-R.CCCCC",
        "m/s",
        "diffusion mass transfer coefficient at right (outside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-POOL-FRAC-L.CCCCC",
        "none",
        "fraction of left (inside) boundary surface of Heat Structure CCCCC in pool of its boundary volume .",
    ),
    (
        "HS-POOL-FRAC-R.CCCCC",
        "none",
        "fraction of right (outside) boundary surface of Heat Structure CCCCC in pool of its boundary volume",
    ),
    (
        "HS-QFLUX-ATMS-L.CCCCC",
        "W/m2",
        "heat flux to atmosphere at left (inside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-QFLUX-ATMS-R.CCCCC",
        "W/m2",
        "heat flux to atmosphere at right (outside) boundary surface of Heat Structure CCCCC .",
    ),
    (
        "HS-QFLUX-POOL-L.CCCCC",
        "W/m2",
        "heat flux to pool at left (inside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-QFLUX-POOL-R.CCCCC",
        "W/m2",
        "heat flux to pool at right (outside) boundary surface of Heat Structure CCCCC.",
    ),
    (
        "HS-QTOTAL-ATMS-L.CCCCC",
        "J",
        "time and surface integral of heat flux to atmosphere at left (inside) boundary surface of Heat Structure CCCCC.",
    ),
    (
        "HS-QTOTAL-ATMS-R.CCCCC",
        "J",
        "time and surface integral of heat flux to atmosphere at right (outside) boundary surface of Heat Structure CCCCC.",
    ),
    (
        "HS-QTOTAL-POOL-L.CCCCC",
        "J",
        "time and surface integral of heat flux to pool at left (inside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-QTOTAL-POOL-R.CCCCC",
        "J",
        "time and surface integral of heat flux to pool at right (outside) boundary surface of Heat Structure CCCCC.",
    ),
    ("HS-TEMP.CCCCCMN", "K", "temperature at node MN of Heat Structure CCCCC."),
    ("RN1-CPUC", "s", "Total time for the run routines of the RN1 package."),
    ("RN1-CPUE", "s", "Total time for the edit routines of the RN1 package."),
    ("RN1-CPUR", "s", "Total time for the restart routines of the RN1 package."),
    ("RN1-CPUT", "s", "Sum of the run, edit and restart times of the RN1 package."),
    (
        "RN1-ATMG.cv",
        "kg",
        "Total mass of aerosol (radioactive plus nonradioactive) in the gas phase, for each control volume cv.",
    ),
    (
        "RN1-ARMG.cv",
        "kg",
        "Total mass of radioactive aerosol in the gas phase, for each control volume cv.",
    ),
    (
        "RN1-VTMG.cv",
        "kg",
        "Total mass of fission product vapor (radioactive plus nonradioactive) in the gas phase, for each control volume cv.",
    ),
    (
        "RN1-VRMG.cv",
        "kg",
        "Total mass of radioactive fission product vapor in the gas phase, for each control volume cv.",
    ),
    (
        "RN1-ATML.cv",
        "kg",
        "Total mass of aerosol (radioactive plus nonradioactive) in the liquid phase, for each control volume cv.",
    ),
    (
        "RN1-ARML.cv",
        "kg",
        "Total mass of radioactive aerosol in the liquid phase, for each control volume cv.",
    ),
    (
        "RN1-VTML.cv",
        "kg",
        "Total mass of fission product vapor (radioactive plus nonradioactive) in the liquid phase, for each control volume cv.",
    ),
    (
        "RN1-VRML.cv",
        "kg",
        "Total mass of radioactive fission product vapor in the liquid phase, for each control volume cv.",
    ),
    (
        "RN1-XMRLSE-x-y.cv",
        "kg",
        "Total mass of class x released from COR components in control volume cv. The parameter y specifies total mass (y=1) or radioactive mass only (y=2).",
    ),
    (
        "RN1-XMRLSET",
        "kg",
        "Total non-radioactive plus radioactive mass released from COR components.",
    ),
    ("RN1-XMRLSER", "kg", "Total radioactive mass released from COR components."),
    (
        "RN1-AMG-w-x-y.cv",
        "kg",
        "Aerosol mass of section w, class x, in the atmosphere of control volume cv not including aerosols deposited on heat structures. The parameter y specifies total mass (y=1) or radioactive mass only (y=2).",
    ),
    (
        "RN1-VMG-x-y.cv",
        "kg",
        "Vapor mass of class x, in the atmosphere of control volume cv not including vapor deposited on heat structures. The parameter y specifies total mass (y=1) or radioactive mass only (y=2).",
    ),
    (
        "RN1-AML-x-y.cv",
        "kg",
        "Aerosol mass of class x, in the pool of control volume cv not including aerosols deposited on heat structures. The parameter Y specifies total mass (y=1) or radioactive mass only (y=2).",
    ),
    (
        "RN1-VML-x-y.cv",
        "kg",
        "Vapor mass of class x, in the pool of control volume cv not including vapor deposited on heat structures. The parameter y specifies either total mass (y=1) or radioactive mass only (y=2).",
    ),
    (
        "RN1-ADEP-s-x-y.hs",
        "kg",
        "Aerosol mass of class x, deposited on side s (s=1 is the LHS, s=2 is the RHS) of heat structure hs. The parameter y specifies total mass (y=1) or radioactive mass only (y=2).",
    ),
    (
        "RN1-VDEP-s-x-y.hs",
        "kg",
        "Vapor mass of class x, deposited on side s (s=1 is the LHS, s=2 is the RHS) of heat structure hs. The parameter y specifies total mass (y=1) or radioactive mass only (y=2).",
    ),
    (
        "RN1-ATMT",
        "kg",
        "Total radioactive plus non-radioactive aerosol mass in the atmosphere and pool regions, not including deposited aerosols on heat structures.",
    ),
    (
        "RN1-ATMR",
        "kg",
        "Total radioactive aerosol mass in the atmosphere and pool regions, not including deposited aerosols on heat structures.",
    ),
    (
        "RN1-VTMT",
        "kg",
        "Total radioactive plus non-radioactive fission product vapor mass in the atmosphere and pool regions, not including deposited vapors on heat structures.",
    ),
    (
        "RN1-VTMR",
        "kg",
        "Total radioactive fission product vapor mass in the atmosphere and pool regions, not including deposited vapors on heat structures.",
    ),
    (
        "RN1-TMT",
        "kg",
        "Total radioactive and non-radioactive aerosol and fission product vapor masses in the atmosphere and pool regions. Equal to RN1-ATMT plus RN1-VTMT variables.",
    ),
    (
        "RN1-TMR",
        "kg",
        "Total radioactive aerosol and fission product vapor masses in the atmosphere and pool regions. Equal to RN1-ATMR plus RN1-VTMR variables.",
    ),
    (
        "RN1-MDTT-n-y",
        "kg",
        "Total radioactive and non-radioactive mass deposited on heat structure n (user number) on side y. The values of y are 1 for the LHS and 2 for the RHS.",
    ),
    (
        "RN1-MDTR-n-y",
        "kg",
        "Total radioactive mass deposited on heat structure n (user number) on side y. The values of y are 1 for the LHS and 2 for the RHS.",
    ),
    (
        "RN1-TMDTT",
        "kg",
        "Total radioactive and non-radioactive mass deposited on all heat structures.",
    ),
    ("RN1-TMDTR", "kg", "Total radioactive mass deposited on all heat structures."),
    (
        "RN1-DHTOT",
        "W",
        "Total decay heat calculated by RadioNuclide package for all locations of radionuclides.",
    ),
    ("RN1-DHCOR", "W", "Total decay heat from the radionuclides in the core."),
    ("RN1-DHCAV", "W", "Total decay heat from the radionuclides in the cavity."),
    (
        "RN1-DHDEP",
        "W",
        "Total decay heat from the radionuclides deposited on the heat structures.",
    ),
    ("RN1-DHATM", "W", "Total decay heat from airborne radionuclides."),
    ("RN1-DHPOL", "W", "Total decay heat from radionuclides in the pool."),
    (
        "RN1-AMGT-x-y.cv",
        "kg",
        "Aerosol mass of class x in the atmosphere of control volume cv (sum of sections), not including aerosols deposited on heat structures. The parameter y specifies either total mass (y=1) or just the radioactive mass (y=2).",
    ),
    (
        "RN1-CVCLT-x-y.cv",
        "kg",
        "Total mass of class x as aerosol and vapor in control volume cv. Includes mass in pool and atmosphere, but not thatdeposited on heat structures. The parameter y specifies either total mass (y=1) or just the radioactive mass (y=2).",
    ),
    (
        "RN1-CVTOT-y.cv",
        "kg",
        "Mass of radionuclides in control volume cv. Includes mass in pool and atmosphere, but not that deposited on heat structures. The parameter y specifies either total mass (y=1) or just the radioactive mass (y=2).",
    ),
    (
        "RN1-TYTOT-1.ty",
        "kg",
        "Sum of total masses of radionuclides in all control volumes of type ty. Includes mass in pool and atmosphere, but not that deposited on heat structures.",
    ),
    (
        "RN1-TYTOT-2.ty",
        "kg",
        "Sum of radioactive masses of radionuclides in all control volumes of type ty. Includes mass in pool and atmosphere, but not that deposited on heat structures.",
    ),
    (
        "RN1-MMDW.cv",
        "m",
        "Mass median diameter of the wet aerosol distribution in the gas phase for each control volume cv.",
    ),
    (
        "RN1-GSDW.cv",
        "none",
        "Geometric standard deviation of the wet aerosol distribution in the gas phase for each control volume cv.",
    ),
    (
        "RN1-MMDD.cv",
        "m",
        "Mass median diameter of the dry aerosol distribution in the gas phase for each control volume cv.",
    ),
    (
        "RN1-GSDD.cv",
        "none",
        "Geometric standard deviation of the dry aerosol distribution in the gas phase for each control volume cv.",
    ),
    (
        "RN1-MMDC-x.cv",
        "m",
        "Mass median diameter of component x in the aerosol distribution in the gas phase for each control volume cv.",
    ),
    (
        "RN1-GSDC-x.cv",
        "none",
        "Geometric standard deviation of component x in the aerosol distribution in the gas phase for each control volume cv.",
    ),
    ("RN2-CPUC", "s", "Total time for the run routines of the RN2 package."),
    ("RN2-CPUE", "s", "Total time for the edit routines of the RN2 package."),
    ("RN2-CPUR", "s", "Total time for the restart routines of the RN2 package."),
    ("RN2-CPUT", "s", "Sum of the run, edit and restart times of the RN2 package."),
    (
        "RN2-AMFLT-x.f",
        "kg",
        "Total aerosol mass of class x on filter f, where f is the filter number.",
    ),
    ("RN2-AMFLT.f", "kg", "Total aerosol mass on filter f (sum of RN2-AMFLT-x.f)"),
    ("RN2-VMFLT-x.f", "kg", "Total vapor mass of class x on filter f."),
    ("RN2-VMFLT.f", "kg", "Total vapor mass on filter f (sum of RN2-VMFLT-x.f)."),
    (
        "RN2-FLT-QTOT.f",
        "W",
        "Total decay heat from all radionuclides deposited on filter f.",
    ),
    (
        "RN2-FLT-QLOS.f",
        "W",
        "Heat loss from filter f (portion of RN2-FLT-QTOT that is assumed to be lost from the system).",
    ),
    ("RN2-VFLT-TMP.f", "K", "Temperature of charcoal bed in vapor filter f."),
    (
        "RN2-VFLT-RAD.f",
        "kg/s",
        "Radiolytic desorption rate of fission product vapors from filter f.",
    ),
    (
        "RN2-VFLT-THR.f",
        "kg/s",
        "Thermal desorption rate of fission product vapors from filter f.",
    ),
    (
        "RN2-VFLT-BUR.f",
        "kg/s",
        "Rate of fission product vapor release from filter f due to charcoal combustion.",
    ),
    (
        "RN2-DFBUB-w.ip",
        "none",
        "Instantaneous decontamination factor of aerosols in mass section w from pool scrubbing associated with path ip. (ip=10*NFL+1 for the from volume associated with flow path NFL, ip=10*NFL+2 for the to volume associated with flow path NFL, and ip=10*NCAV for the pool associated with cavity NCAV.)",
    ),
    (
        "RN2-DFBUB-a.ip",
        "none",
        "(a=NUMSEC+1) Instantaneous decontamination factor of total aerosol mass from pool scrubbing associated with path ip. (ip=10*NFL+1 for the from volume associated with flow path NFL, ip=10*NFL+2 for the to volume associated with flow path NFL, and ip=10*NCAV for the pool associated with cavity NCAV.)",
    ),
    (
        "RN2-DFBUB-v.ip",
        "none",
        "(v=NUMSEC+1+x) Instantaneous decontamination factor of vapor in class x from pool scrubbing associated with path ip. (ip=10*NFL+1 for the from volume associated with flow path NFL, ip=10*NFL+2 for the to volume associated with flow path NFL, and ip=10*NCAV for the pool associated with cavity NCAV.) Currently, only x=4 is calculated.",
    ),
    (
        "RN2-DFBBT-w.ip",
        "none",
        "Cumulative decontamination factor of aerosols in mass section w from pool scrubbing associated with path ip. (ip=10*NFL+1 for the from volume associated with flow path NFL, ip=10*NFL+2 for the to volume associated with flow path NFL, and ip=10*NCAV for the pool associated with cavity NCAV.)",
    ),
    (
        "RN2-DFBBT-a.ip",
        "none",
        "(a=NUMSEC+1) Cumulative decontamination factor of total aerosol mass from pool scrubbing associated with path ip. (ip=10*NFL+1 for the from volume associated with flow path NFL, ip=10*NFL+2 for the to volume associated with flow path NFL, and ip=10*NCAV for the pool associated with cavity NCAV.)",
    ),
    (
        "RN2-DFBBT-v.ip",
        "none",
        "(v=NUMSEC+1+x) Cumulative decontamination factor of vapor in class x from pool scrubbing associated with path ip. (ip=10*NFL+1 for the from volume associated with flow path NFL, ip=10*NFL+2 for the to volume associated with flow path NFL, and ip=10*NCAV for the pool associated with cavity NCAV.) Currently, only x=4 is calculated.",
    ),
    (
        "COR-T-LP-MP1.1",
        "K",
        "Temperature of lower plenum convecting molten oxidic pool in channel.",
    ),
    (
        "COR-T-LP-MP1.2",
        "K",
        "Temperature of lower plenum convecting molten oxidic pool in bypass.",
    ),
    (
        "COR-T-LP-MP2.1",
        "K",
        "Temperature of lower plenum convecting metallic molten pool in channel.",
    ),
    (
        "COR-T-LP-MP2.2",
        "K",
        "Temperature of lower plenum convecting metallic molten pool in bypass.",
    ),
    (
        "COR-T-UP-MP1.1",
        "K",
        "Temperature of upper core convecting oxidic molten pool in channel.",
    ),
    (
        "COR-T-UP-MP1.2",
        "K",
        "Temperature of upper core convecting oxidic molten pool in bypass.",
    ),
    (
        "COR-T-UP-MP2.1",
        "K",
        "Temperature of upper core convecting metallic molten pool in channel.",
    ),
    (
        "COR-T-UP-MP2.2",
        "K",
        "Temperature of upper core convecting metallic molten pool in bypass.",
    ),
    (
        "COR-M-LP-MP1.1",
        "kg",
        "Total mass of lower plenum convecting oxidic molten pool in channel.",
    ),
    (
        "COR-M-LP-MP1.2",
        "kg",
        "Total mass of lower plenum convecting oxidic molten pool in bypass.",
    ),
    (
        "COR-M-LP-MP2.1",
        "kg",
        "Total mass of lower plenum convecting metallic molten pool in channel.",
    ),
    (
        "COR-M-",
        "kg",
        "Total mass of lower plenum convecting metallic molten pool in bypass.",
    ),
    (
        "COR-M-UP-MP1.1",
        "kg",
        "Total mass of upper core convecting oxidic molten pool in channel.",
    ),
    (
        "COR-M-UP-MP1.2",
        "kg",
        "Total mass of upper core convecting oxidic molten pool in bypass.",
    ),
    (
        "COR-M-UP-MP2.1",
        "kg",
        "Total mass of upper core convecting metallic molten pool in channel.",
    ),
    (
        "COR-M-UP-MP2.2",
        "kg",
        "Total mass of upper core convecting metallic molten pool in bypass.",
    ),
    (
        "COR-MP-V-COR1.1",
        "m3",
        "Volume of upper core convecting oxidic molten pool in channel.",
    ),
    (
        "COR-MP-V-COR1.1",
        "m3",
        "Volume of upper core convecting molten oxidic pool in bypass.",
    ),
    (
        "COR-MP-V-COR2.1",
        "m3",
        "Volume of upper core convecting metallic molten pool in channel.",
    ),
    (
        "COR-MP-V-COR2.2",
        "m3",
        "Volume of upper core convecting metallic molten pool in bypass.",
    ),
    (
        "COR-MP-V-LP1.1",
        "m3",
        "Volume of lower plenum convecting oxidic molten pool in channel.",
    ),
    (
        "COR-MP-V-LP1.1",
        "m3",
        "Volume of lower plenum convecting oxidic molten pool in bypass.",
    ),
    (
        "COR-MP-V-LP2.1",
        "m3",
        "Volume of lower plenum convecting metallic molten pool in channel.",
    ),
    (
        "COR-MP-V-LP2.2",
        "m3",
        "Volume of lower plenum convecting metallic molten pool in bypass.",
    ),
    (
        "COR-MP-RA1-COR1.1",
        "m3",
        "Rayleigh number of upper core convecting oxidic molten pool in channel.",
    ),
    (
        "COR-MP-RA1-COR1.1",
        "m3",
        "Vol Rayleigh number of upper core oxidic convecting molten pool in bypass.",
    ),
    (
        "COR-MP-RA1-COR2.1",
        "m3",
        "Rayleigh number of upper core convecting metallic molten pool in channel.",
    ),
    (
        "COR-MP-RA1-COR2.2",
        "m3",
        "Rayleigh number of upper core convecting metallic molten pool in bypass.",
    ),
    (
        "COR-MP-RA1-LP1.1",
        "m3",
        "Rayleigh number of lower plenum convecting oxidic molten pool in channel.",
    ),
    (
        "COR-MP-RA1-LP1.1",
        "m3",
        "Rayleigh number of lower plenum convecting oxidic molten pool in bypass.",
    ),
    (
        "COR-MP-RA1-LP2.1",
        "m3",
        "Rayleigh number of lower plenum convecting metallic molten pool in channel.",
    ),
    (
        "COR-MP-RA1-LP2.2",
        "m3",
        "Rayleigh number of lower plenum convecting metallic molten pool in bypass.",
    ),
    (
        "COR-MPr-UP-CH-OX.n",
        "kg",
        "Mass of radionuclides in upper plenum oxide molten pool in cell n.",
    ),
    (
        "COR-MPr-UP-CH-MT.n",
        "kg",
        "Mass of radionuclides in upper plenum metallic molten pool in cell n.",
    ),
    (
        "COR-MPr-UP-BY-OX.n",
        "kg",
        "Mass of radionuclides in upper plenum oxide molten pool in bypass in cell n.",
    ),
    (
        "COR-MPr-UP-BY-MT.n",
        "kg",
        "Mass of radionuclides in upper plenum metallic molten pool in bypass in cell n.",
    ),
    (
        "COR-MPr-LP-CH-OX.n",
        "kg",
        "Mass of radionuclides in lower plenum oxide molten pool in cell n.",
    ),
    (
        "COR-MPr-LP-CH-MT.n",
        "kg",
        "Mass of radionuclides in lower plenum metallic molten pool in cell n.",
    ),
    (
        "COR-MPr-LP-BY-OX.n",
        "kg",
        "Mass of radionuclides in lower plenum oxide molten pool in bypass in cell n.",
    ),
    (
        "COR-MPr-LP-BY-MT.n",
        "kg",
        "Mass of radionuclides in lower plenum metallic molten pool in bypass in cell n.",
    ),
    ("COR-TSH.n", "K", "Temperature of PWR core shroud in cell n."),
    ("COR-TFM.n", "K", "Temperature of PWR core former in cell n."),
    ("COR-TMP1.n", "K", "Temperature of oxidic molten pool 1 material in cell n."),
    ("COR-TMP2.n", "K", "Temperature of metallic molten pool 2 material in cell n."),
    (
        "COR-TMB1.n",
        "K",
        "Temperature of oxidicmolten pool 1material in bypass of cell n.",
    ),
    (
        "COR-TMB2.n",
        "K",
        "Temperature of metallic molten pool 2 material in bypass of cell n.",
    ),
    (
        "COR-DMH2-SS",
        "kg",
        "Total cumulative hydrogen production by oxidation of stainless steel in core.",
    ),
    (
        "COR-DMH2-ZIRC",
        "kg",
        "Total cumulative hydrogen production by oxidation of Zircaloy in core.",
    ),
    (
        "COR-DMH2-B4C",
        "kg",
        "Total cumulative hydrogen production by oxidation of boron carbide in core.",
    ),
    (
        "COR-MASS-DISCARD",
        "kg",
        "Total accumulated mass of discarded components of “negligible” mass.",
    ),
    (
        "COR-ENGY-DISCARD",
        "J",
        "Total accumulated energy associated with discarded components of “negligible” mass.",
    ),
    ("COR-VOLF-SH.n", "none", "PWR core shroud volume fraction in cell n."),
    ("COR-VOLF-FM.n", "none", "PWR core former volume fraction in cell n."),
    ("COR-VOLF-MP1.n", "none", "Molten pool 1 (oxide) volume fraction in cell n."),
    (
        "COR-VOLF-MB1.n",
        "none",
        "Molten pool 1 (oxide) volume fraction in bypass of cell n.",
    ),
    ("COR-VOLF-MP2.n", "none", "Molten pool 2 (metallic) volume fraction in cell n."),
    (
        "COR-VOLF-MB2.n",
        "none",
        "Molten pool 2 (metallic) volume fraction in bypass of cell n.",
    ),
    (
        "COR-ZQ-CL.n",
        "m",
        "Position of the quench front on the surface of cladding in cell n. It is returned as the elevation of the bottom of the cell if the entire surface is unquenched and as the elevation of the top of the cell if it is quenched.",
    ),
    (
        "COR-TQ-CL.n",
        "K",
        "Temperature of the quenched portion of the surface of cladding in cell n. If there is no quench front in the core cell, it is returned as the average temperature.",
    ),
    (
        "COR-TUQ-CL.n",
        "K",
        "Temperature of the unquenched portion of the surface of cladding in cell n. If there is no quench front in the core cell, it is returned as the average temperature.",
    ),
    (
        "CVH-ATM-FR.n",
        "none",
        "Atmosphere (nonpool) volume fraction in control volume n, equivalent to the previous variable CVH-VOID.n.",
    ),
    (
        "CVH-VOID-P.n",
        "none",
        "Void (bubble) volume fraction in pool of control volume n.",
    ),
    (
        "CVH-VOID-T.n",
        "none",
        "Total void (nonliquid) volume fraction in control volume n, including the atmosphere and bubbles in the pool.",
    ),
    (
        "HS-DEGAS-STEELM.GGGGG",
        "kg",
        "Steel mass melted during the system cycle for steel degassing source GGGGG",
    ),
    (
        "HS-DEGAS-CSTEELM.GGGGG",
        "kg",
        "Cumulative mass of steel melted for steel degassing source GGGGG",
    ),
    (
        "RN1-GSDC-1.cv",
        "none",
        "Geometric standard deviation of component 1 in the aerosol distribution in the gas phase for each control volume cv.",
    ),
    (
        "RN1-GSDC-2.cv",
        "none",
        "Geometric standard deviation of component 2 in the aerosol distribution in the gas phase for each control volume cv.",
    ),
    (
        "RN1-MCAT-n-y",
        "kg",
        "Total mass chemisorbed on side y of heat structure n (user number). The LHS is y=1 and the RHS is y=2.",
    ),
    (
        "RN1-MCAR-n-y",
        "kg",
        "Total radioactive mass chemisorbed on side y of heat structure n (user number). The LHS is y=1 and the RHS is y=2.",
    ),
    (
        "RN1-TMCAT",
        "kg",
        "Total mass of chemisorbed species deposited on all heat structures.",
    ),
    (
        "RN1-TMCAR",
        "kg",
        "Total radioactive mass of chemisorbed species deposited on all heat structures.",
    ),
    (
        "RN1-TOTMAS-y.x",
        "kg",
        "Sum of masses of class x in all locations, excluding that not yet released from fuel or debris. The parameter y specifies either total mass (y=1) or just the radioactive mass (y=2).",
    ),
    ("RN1-PH.nnn", "none", "pH of pool in control volume nnn."),
    ("CAV-ASURF.n", "m2", "Area of upper surface of debris pool."),
    ("CAV-CRUSTB.lay.n", "m", "Thickness of frozen crust on lower surface."),
    ("CAV-CRUSTT.lay.n", "m", "Thickness of frozen crust on upper surface."),
    ("CAV-TSURF.n", "K", "Temperature of upper surface of debris pool."),
    ("CAV-MASSERR.n", "kg", "Area of upper surface of debris pool."),
    ("CAV-ENERGYERR.n", "J", "Area of upper surface of debris pool."),
    ("ESF-QFC-RAT.n", "W", "Heat transfer rate for fan cooler n."),
    ("ESF-QFC-TOT.n", "J", "Total energy transfer for fan cooler n."),
    ("ESF-MFC-RAT.n", "kg/s", "Condensation rate for fan cooler n."),
    ("ESF-MFC-TOT.n", "kg", "Total steam condensed for fan cooler n."),
    ("ESF-PAR-DMH2.n", "kg/s", "Per PAR unit H2 removal rate for PAR n."),
    ("ESF-PAR-IMH2.n", "kg", "Total H2 removed for all FPARD units of PAR n."),
    ("ESF-PAR-DVOL.n", "m3/s", "Per PAR unit total gas flow rate for PAR n."),
    (
        "ESF-PAR-IVOL.n",
        "m3",
        "Total volume of gas processed in all FPARD units of PAR n.",
    ),
    ("ESF-PAR-TOUT.n", "m3/s", "Outlet gas temperature for PAR n."),
    ("ESF-PAR-FMOL.n", "m3", "Outlet gas H2 mole fraction for PAR n."),
    (
        "esf-pccs-vntfl",
        "kg",
        "The integrated total flow through the PCCS vent line into the pressure suppression pool.",
    ),
    (
        "esf-pccs-toteng",
        "J",
        "Integrated energy added to the ICS/PCC pools (PCCS heat sink).",
    ),
    ("esf-pccs-totstm", "kg", "Cumulative steam removed from the drywell."),
    (
        "esf-ics-vntfl",
        "kg",
        "The integrated total flow through the ICS vent line into the pressure suppression pool.",
    ),
    (
        "esf-ics-toteng",
        "J",
        "Integrated energy added to the ICS/PCC pools (ICS heat sink).",
    ),
    ("esf-ics-toststm", "kg", "Cumulative steam removed from the reactor vessel."),
    (
        "RN1-TYCLT-x-n.ty",
        "kg",
        "Total mass (n=1) or radioactive mass (n=2) of class x in all control volumes of type ty, including mass deposited on heat structures associated with the control volumes.",
    ),
    (
        "RN1-TYCLT-x-1.ty",
        "kg",
        "Total mass of class x in all control volumes of type ty, including mass deposited on heat structures associated with the control volumes.",
    ),
    (
        "RN1-TYCLT-x-2.ty",
        "kg",
        "Radioactive mass of class x in all control volumes of type ty, including mass deposited on heat structures associated with the control volumes.",
    ),
    (
        "HS-RAD-FLUX-L.CCCCC",
        "W/m**2",
        "Total structure-to-structure radiation to radiative heat flux from left (inside) boundary surface of Heat Structure CCCCC",
    ),
    (
        "HS-RAD-FLUX-R.CCCCC",
        "W/m**2",
        "Total structure-to-structure radiation to radiative heat flux from right (outside) boundary surface of Heat Structure CCCCC",
    ),
]
